org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=/Users/shuqishen/jdk25/Contents/Home
org.gradle.parallel=true

mod_version=1.10
maven_group=starship.cfm
archives_base_name=template-mod

minecraft_version=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

fabric_api_version=0.145.1+26.1
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
